version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./db/private_key.json:/app/credentials/private_key.json:ro
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/private_key.json
